version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/database
      - .env/development/web
    # environment:
    #   - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server

  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/api
      - gem_cache:/gems
    env_file:
      - .env/development/database
      - .env/development/web

  # webpack_dev_server:
  #   build: .
  #   command: ./bin/webpack-dev-server
  #   ports:
  #     - "3035:3035"
  #   volumes:
  #     - .:/usr/src/app
  #     - gem_cache:/gems
  #   env_file:
  #     - .env/development/database
  #     - .env/development/web
  #   environment:
  #     - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  # redis:
  #   image: redis

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

  # selenium_chrome:
  #   image: selenium/standalone-chrome-debug
  #   logging:
  #     driver: none
  #   ports:
  #     - "5900:5900"

volumes:
  db_data:
  gem_cache:
